# Generated by Django 3.0.2 on 2021-12-08 04:31

import contents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastEditDate', models.DateTimeField(auto_now=True)),
                ('is_Accepted', models.BooleanField(default=True)),
                ('contentType', models.CharField(choices=[('Image', 'Img'), ('Video', 'VOD')], default='', max_length=200, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=contents.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('themeValue', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('theme_id', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.CASCADE, related_name='Detail_Theme', to='contents.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Contents_Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', tinymce.models.HTMLField()),
                ('contentFK', models.ForeignKey(blank=True, db_column='contentsFK', null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='theme_id',
            field=models.ForeignKey(blank=True, db_column='theme_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contents.Theme'),
        ),
        migrations.AddField(
            model_name='contents',
            name='userFK',
            field=models.ForeignKey(db_column='userFK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Content_Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contents_id', models.ForeignKey(db_column='contents_id', on_delete=django.db.models.deletion.CASCADE, related_name='Content_Like', to='contents.Contents')),
                ('userFK', models.ForeignKey(db_column='userFK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contents_id', models.ForeignKey(db_column='contents_id', on_delete=django.db.models.deletion.CASCADE, related_name='Content_Comment', to='contents.Contents')),
                ('userFK', models.ForeignKey(db_column='userFK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
