# Generated by Django 4.0.1 on 2022-02-11 09:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='CMS USER', max_length=50, null=True)),
                ('user_description', models.TextField(blank=True, default=0, max_length=500, null=True)),
                ('user_profile', models.FileField(blank=True, null=True, upload_to=user.models.profile_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('user_auth', models.CharField(choices=[('SUPER_ADMIN', 'Super_Admin'), ('SHELTER_ADMIN', 'Shelter_Admin'), ('CONTENTS_CREATOR', 'Contents_CREATOR'), ('USER', 'User')], default=0, max_length=200, null=True)),
                ('user', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
